import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const CORZ_EXPERIMENTAL = truthy("CORZ_EXPERIMENTAL")
const CORZ_DISABLE_CLAUDE_CODE = truthy("CORZ_DISABLE_CLAUDE_CODE")
const CORZ_DISABLE_CLAUDE_CODE_SKILLS =
  CORZ_DISABLE_CLAUDE_CODE || truthy("CORZ_DISABLE_CLAUDE_CODE_SKILLS")
const copy = process.env["CORZ_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  CORZ_AUTO_SHARE: truthy("CORZ_AUTO_SHARE"),
  CORZ_AUTO_HEAP_SNAPSHOT: truthy("CORZ_AUTO_HEAP_SNAPSHOT"),
  CORZ_GIT_BASH_PATH: process.env["CORZ_GIT_BASH_PATH"],
  CORZ_CONFIG: process.env["CORZ_CONFIG"],
  CORZ_CONFIG_CONTENT: process.env["CORZ_CONFIG_CONTENT"],
  CORZ_DISABLE_AUTOUPDATE: truthy("CORZ_DISABLE_AUTOUPDATE"),
  CORZ_ALWAYS_NOTIFY_UPDATE: truthy("CORZ_ALWAYS_NOTIFY_UPDATE"),
  CORZ_DISABLE_PRUNE: truthy("CORZ_DISABLE_PRUNE"),
  CORZ_DISABLE_TERMINAL_TITLE: truthy("CORZ_DISABLE_TERMINAL_TITLE"),
  CORZ_SHOW_TTFD: truthy("CORZ_SHOW_TTFD"),
  CORZ_PERMISSION: process.env["CORZ_PERMISSION"],
  CORZ_DISABLE_DEFAULT_PLUGINS: truthy("CORZ_DISABLE_DEFAULT_PLUGINS"),
  CORZ_DISABLE_LSP_DOWNLOAD: truthy("CORZ_DISABLE_LSP_DOWNLOAD"),
  CORZ_ENABLE_EXPERIMENTAL_MODELS: truthy("CORZ_ENABLE_EXPERIMENTAL_MODELS"),
  CORZ_DISABLE_AUTOCOMPACT: truthy("CORZ_DISABLE_AUTOCOMPACT"),
  CORZ_DISABLE_MODELS_FETCH: truthy("CORZ_DISABLE_MODELS_FETCH"),
  CORZ_DISABLE_MOUSE: truthy("CORZ_DISABLE_MOUSE"),
  CORZ_DISABLE_CLAUDE_CODE,
  CORZ_DISABLE_CLAUDE_CODE_PROMPT: CORZ_DISABLE_CLAUDE_CODE || truthy("CORZ_DISABLE_CLAUDE_CODE_PROMPT"),
  CORZ_DISABLE_CLAUDE_CODE_SKILLS,
  CORZ_DISABLE_EXTERNAL_SKILLS: truthy("CORZ_DISABLE_EXTERNAL_SKILLS"),
  CORZ_FAKE_VCS: process.env["CORZ_FAKE_VCS"],
  CORZ_SERVER_PASSWORD: process.env["CORZ_SERVER_PASSWORD"],
  CORZ_SERVER_USERNAME: process.env["CORZ_SERVER_USERNAME"],
  CORZ_ENABLE_QUESTION_TOOL: truthy("CORZ_ENABLE_QUESTION_TOOL"),

  // License activation
  CORZ_AUTH_URL: process.env["CORZ_AUTH_URL"],
  CORZ_AUTH_TIMEOUT_MS: number("CORZ_AUTH_TIMEOUT_MS"),
  CORZ_AUTH_MAX_RETRIES: number("CORZ_AUTH_MAX_RETRIES"),
  CORZ_AUTH_RETRY_DELAY_MS: number("CORZ_AUTH_RETRY_DELAY_MS"),
  CORZ_CONVEX_SHARED_SECRET: process.env["CORZ_CONVEX_SHARED_SECRET"],
  CORZ_DISABLE_LICENSE_GATE: truthy("CORZ_DISABLE_LICENSE_GATE"),

  // Experimental
  CORZ_EXPERIMENTAL,
  CORZ_EXPERIMENTAL_FILEWATCHER: Config.boolean("CORZ_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  CORZ_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("CORZ_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  CORZ_EXPERIMENTAL_ICON_DISCOVERY: CORZ_EXPERIMENTAL || truthy("CORZ_EXPERIMENTAL_ICON_DISCOVERY"),
  CORZ_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("CORZ_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  CORZ_ENABLE_EXA: truthy("CORZ_ENABLE_EXA") || CORZ_EXPERIMENTAL || truthy("CORZ_EXPERIMENTAL_EXA"),
  CORZ_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("CORZ_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  CORZ_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("CORZ_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  CORZ_EXPERIMENTAL_OXFMT: CORZ_EXPERIMENTAL || truthy("CORZ_EXPERIMENTAL_OXFMT"),
  CORZ_EXPERIMENTAL_LSP_TY: truthy("CORZ_EXPERIMENTAL_LSP_TY"),
  CORZ_EXPERIMENTAL_LSP_TOOL: CORZ_EXPERIMENTAL || truthy("CORZ_EXPERIMENTAL_LSP_TOOL"),
  CORZ_EXPERIMENTAL_PLAN_MODE: CORZ_EXPERIMENTAL || truthy("CORZ_EXPERIMENTAL_PLAN_MODE"),
  CORZ_EXPERIMENTAL_SCOUT: CORZ_EXPERIMENTAL || truthy("CORZ_EXPERIMENTAL_SCOUT"),
  CORZ_EXPERIMENTAL_MARKDOWN: !falsy("CORZ_EXPERIMENTAL_MARKDOWN"),
  CORZ_ENABLE_PARALLEL: truthy("CORZ_ENABLE_PARALLEL") || truthy("CORZ_EXPERIMENTAL_PARALLEL"),
  CORZ_MODELS_URL: process.env["CORZ_MODELS_URL"],
  CORZ_MODELS_PATH: process.env["CORZ_MODELS_PATH"],
  CORZ_DISABLE_EMBEDDED_WEB_UI: truthy("CORZ_DISABLE_EMBEDDED_WEB_UI"),
  CORZ_DB: process.env["CORZ_DB"],
  CORZ_DISABLE_CHANNEL_DB: truthy("CORZ_DISABLE_CHANNEL_DB"),
  CORZ_SKIP_MIGRATIONS: truthy("CORZ_SKIP_MIGRATIONS"),
  CORZ_STRICT_CONFIG_DEPS: truthy("CORZ_STRICT_CONFIG_DEPS"),

  CORZ_WORKSPACE_ID: process.env["CORZ_WORKSPACE_ID"],
  CORZ_EXPERIMENTAL_WORKSPACES: CORZ_EXPERIMENTAL || truthy("CORZ_EXPERIMENTAL_WORKSPACES"),
  CORZ_EXPERIMENTAL_EVENT_SYSTEM: CORZ_EXPERIMENTAL || truthy("CORZ_EXPERIMENTAL_EVENT_SYSTEM"),
  CORZ_EXPERIMENTAL_SESSION_SWITCHING: CORZ_EXPERIMENTAL || truthy("CORZ_EXPERIMENTAL_SESSION_SWITCHING"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get CORZ_DISABLE_PROJECT_CONFIG() {
    return truthy("CORZ_DISABLE_PROJECT_CONFIG")
  },
  get CORZ_TUI_CONFIG() {
    return process.env["CORZ_TUI_CONFIG"]
  },
  get CORZ_CONFIG_DIR() {
    return process.env["CORZ_CONFIG_DIR"]
  },
  get CORZ_PURE() {
    return truthy("CORZ_PURE")
  },
  get CORZ_PLUGIN_META_FILE() {
    return process.env["CORZ_PLUGIN_META_FILE"]
  },
  get CORZ_CLIENT() {
    return process.env["CORZ_CLIENT"] ?? "cli"
  },
}
